apiVersion: apps/v1
kind: Deployment
metadata:
  name: ia-container-deployment
  labels:
    app: ia-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ia-container
  template:
    metadata:
      labels:
        app: ia-container
    spec:
      containers:
      - name: ia-container
        image: seguridad/siamese:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
      securityContext:
  runAsNonRoot: true
  runAsUser: 10000
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
